### ISSUE TITLE
Elaboration on methods

### ISSUE THREAD

**Issue by Firedrops** [pcahan1/singleCellNet#31]
Hi Authors, 

Could you please elaborate on 
1. how are top differentially expressed genes identified (findClassyGenes/getClassGenes/gnrAll)? Are you using a published DE analysis method? Or looking for the most variable genes (by SD)? Or something else?

2. how is the binary matrix formed? i.e. under what conditions would a particular value be assigned 0 or 1? I could not find other mentions of "Top-Pair transformation" on the internet.

**Comment by yuqiyuqitan** [comment]
1. We simply used a linear regression method to identify the DEs. 
2. It is natural that you couldn't find top-pair transformation elsewhere because we developed the top-pair transformation in this paper which is adapted from [Geman et al., 2004 ](https://www.degruyter.com/view/journals/sagmb/3/1/article-sagmb.2004.3.1.1071.xml.xml). However, you can use the diagram below to understand how intuitively the binarization is performed. We binarized the gene pairs based on the relative expression of two genes.
<img width="411" alt="top-pair-transform" src="https://user-images.githubusercontent.com/19160176/99026380-d8c33480-2538-11eb-97de-9c2e81436c9f.png">

**Comment by Firedrops** [comment]
Thank you for the explanations! That has helped me overcome large knowledge gap in trying to understand the method.

I just have 1 final question:

In practice, I suppose would feed one large matrix as the input, an expanded version of the diagram provided above. Would this look something like this?
```
         Cell a1 | Cell b1 | Cell c1 | Cell ..... n1|
genes i-j
genes j-k
genes ...
```

And also, does the Cell a (subscript 1) simply refer to it being from group 1, i.e. the in-bag training dataset? Or does it indicate some other property of the cell?

**Comment by yuqiyuqitan** [comment]
The cell a (subscript1) is referring to a cell from cell type a. This is in the case of binarization for training data.
