### ISSUE TITLE
error in assign_cate

### ISSUE THREAD

**Issue by roofya** [pcahan1/singleCellNet#49]
Hi

Im applying classifier for query data from the tutorial and I got this error
system.time(crACL <- scn_predict(class_info[['cnProc']], expQuery, nrand = 50))
stQuery <- assign_cate(classRes = crACL, sampTab = stQuery, cThresh = 0.5) 
Error in data.frame(..., check.names = FALSE) : 
 arguments imply differing number of rows: 49471, 49521
I have 49471 cells and I saw that in crACL matrix the number of columns are 49521 which the last 50 are rand. Please advise how I should assign the cells based on score.

Thank you

**Comment by yuqiyuqitan** [comment]
so if you were to have the earlier function to be `crACL <- scn_predict(class_info[['cnProc']], expQuery, nrand = 0)` then when assign_cate() is called, you won't have the cell number difference. Because most people dont find assigning categories to randomly generated cells useful. Alternatively, you can also subset out only the original cells from the SCN classification matrix object (crACL).

**Comment by roofya** [comment]
> so if you were to have the earlier function to be `crACL <- scn_predict(class_info[['cnProc']], expQuery, nrand = 0)` then when assign_cate() is called, you won't have the cell number difference. Because most people dont find assigning categories to randomly generated cells useful. Alternatively, you can also subset out only the original cells from the SCN classification matrix object (crACL).

Thank you so much for your prompt reply. Now its working fine
